### PR TITLE
First class queue support

### PR DESCRIPTION
**Pull request by dmitry-vychikov**
Implementation for https://github.com/hangfire-postgres/Hangfire.PostgreSql/issues/303

**Things to consider**
- Fix is really just enabling the feature inside `HasFeature` method, no extra changes expected
- Upgrading Hangfire.Core package is required in order to override `public override bool HasFeature` method (it was added recently)
    - But upgrading Core will force all postgres consumer to upgrade too which might not be good
    - Please advice how to proceed here. I can see an option like releasing an rc ourselves, but it need to be discussed anyway
- This is in `Draft` until I have some time to at least run a full Hangfire instance properly. I only ran a single test, which seems good, but I'm not confident this didn't break anywhere else. 

New `Queue` property serializes just fine. See the screenshot below.

image

### CODE REVIEW

**Comment by danispir** [comment]
Can we merge this please? It is blocking us after upgrading hangfire core. We can't run jobs on custom queues at runtime and we get the error "System.NotSupportedException: Current storage doesn't support specifying queues directly for a specific job."

**Comment by azygis** [comment]
As @dmitry-vychikov mentioned in the description, he still wants to verify if it's working properly when he has the time, hence it's still a draft. I'm not sure when or if he's going to do that. Maybe this is a reminder if he forgot!

**Comment by dmitry-vychikov** [comment]
Hi @azygis @danispir 
Sorry for being offline for so long.

1) I see that Hangfire has release a stable 1.8 version, so it simplifies things for us greatly.
2) Yes, additional testing is helpful. Though I have a feeling it should raise much problems, but better be safe. @azygis do you know if there is a sample app that I could quickly spin up and run some existing tests?

**Comment by azygis** [comment]
To be fair, we can simply run the CI here. As long as it doesn't break the existing tests, it should be good. Usually what I do personally is just use the containerized PostgreSQL instance locally to run the tests so I don't have to install any instances myself.

**Comment by dmitry-vychikov** [comment]
@azygis 
Can you please trigger CI? It does not allow me without maintainer approval.

image

**Comment by azygis** [comment]
> Total tests: 231
     Passed: 231

Looks good. Disregard the CI status - it fails because of CI permissions which I still had no chance to fix.

**Comment by dmitry-vychikov** [comment]
@azygis I'm good merging as is.

Maybe you would want to push it as `beta` release first? Or whatever you feel is best.

**Comment by azygis** [comment]
One thing - drop the version in csproj from 1.8.4 to 1.8.0 so we're not forcing people to use the version that has _just_ been released.

**Comment by dmitry-vychikov** [comment]
> One thing - drop the Hangfire version in csproj from 1.8.4 to 1.8.0 so we're not forcing people to use the version that has _just_ been released.

Good catch, done

**Comment by danispir** [comment]
Thank you all for being so prompt! I appreciate it. Have a nice day!

**Pull request merged**
