### PR TITLE
Cache all SQL queries using sliding expiration

### LINKED ISSUE #278: Optimisation of SQL generation logic
Whenever some method of `PostgreSqlJobQueue` is executed - a new instance of the String class containing formatted SQL is created.
That puts some footprint on the memory:
image

B/c SQL strings depend on `_storage.Options`, it would be more optimal to create those only once - during `PostgreSqlJobQueue` class construction...

### PR DESCRIPTION
**Pull request by azygis**
Closes #278.

### CODE REVIEW

**Comment by frankhommers** [comment]
I don't really get this. Is building a simple string really slower than retrieving it from cache?

Why are you using expiration? Do you think the options could change over time?

**Comment by azygis** [comment]
The broader discussion is in #278, let's keep it there.

Regarding the expiration - there's no point keeping the queries in memory indefinitely when there is no need for it for an extended period of time, for example any of the dashboard queries are irrelevant, therefore can just expire.

**Comment by frankhommers** [comment]
I would choose a sliding expiration of 2 hours, instead of 30 minutes. That feels more feasible to me.

Did you compare benchmarks of previous versions and this one to compare allocations?

**Comment by azygis** [comment]
I did as mentioned in the [comment](https://github.com/hangfire-postgres/Hangfire.PostgreSql/issues/278#issuecomment-1466456518). It might be that the pull request isn't even worth it, hence it's still idling here. First want to try a few things from the linked issue, but free time is too limited right now.

**Comment by azygis** [comment]
Closing as it's not something that's _really_ beneficial.

**Pull request closed without merging**
